name: profile-test

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  profile-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: '8.3'
      - name: PHP syntax
        run: make syntax
      - name: CLI color test
        run: php -d zend.assertions=1 -d assert.exception=1 tests/cli-style.php
      - name: Semgrep rules
        run: make semgrep-rules
      - name: Profile tests
        run: make profile-test
